[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "oca-sdk"
version = "0.1.0"
description = "Python bindings for the OCA SDK"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "EUPL-1.2" }

[tool.maturin]
module-name = "oca_sdk"
